repos:
-   repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    - id: black
-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    - id: isort
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]